# from: https://karlchris.github.io/data-engineering/projects/spark-docker/#spark-docker-image

services:
  spark-master:
    container_name: spark-master
    build: .
    image: spark-image
    entrypoint: ["./entrypoint.sh", "master"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ../../courses/data_lakes_and_lakehouses/spark-logs:/opt/spark/spark-events
      - ../../courses/data_lakes_and_lakehouses/spark-warehouse:/opt/spark/warehouse
      - ../../courses/data_lakes_and_lakehouses/spark-data:/opt/spark/data
    environment:
      SPARK_NO_DAEMONIZE: "true"
    ports:
      - "8080:8080" # Spark master Web UI
      - "7077:7077" # For spark-node-to-spark-node queries
      - "4040:4040" # Spark worker data
      - "8889:8889" # Optionaly - Jupyter web UI

  spark-history-server:
    container_name: spark-history
    image: spark-image
    entrypoint: ["./entrypoint.sh", "history"]
    depends_on:
      - spark-master
    environment:
      SPARK_NO_DAEMONIZE: "true"
    volumes:
      - ../../courses/data_lakes_and_lakehouses/spark-logs:/opt/spark/spark-events
      - ../../courses/data_lakes_and_lakehouses/spark-warehouse:/opt/spark/warehouse
      - ../../courses/data_lakes_and_lakehouses/spark-data:/opt/spark/data
    ports:
      - "18080:18080"

  spark-connect:
    container_name: spark-connect
    image: spark-image
    entrypoint: ["./entrypoint.sh", "connect"]
    depends_on:
      - spark-master
    environment:
      SPARK_NO_DAEMONIZE: "true"
    volumes:
      - ../../courses/data_lakes_and_lakehouses/spark-logs:/opt/spark/spark-events
      - ../../courses/data_lakes_and_lakehouses/spark-warehouse:/opt/spark/warehouse
      - ../../courses/data_lakes_and_lakehouses/spark-data:/opt/spark/data
    ports:
      - "15002:15002"

  spark-worker:
    container_name: spark-worker
    image: spark-image
    entrypoint: ["./entrypoint.sh", "worker"]
    depends_on:
      - spark-master
    environment:
      SPARK_NO_DAEMONIZE: "true"
    volumes:
      - ../../courses/data_lakes_and_lakehouses/spark-logs:/opt/spark/spark-events
      - ../../courses/data_lakes_and_lakehouses/spark-warehouse:/opt/spark/warehouse
      - ../../courses/data_lakes_and_lakehouses/spark-data:/opt/spark/data
